server:
  port: 8080
management:
  security:
    enabled: false
  endpoints:
    web:
      exposure:
        include: "*"
springdoc:
  swagger-ui:
    path: /docs
spring:
  profiles:
    ## Potential options include kafka, aws, azure
    ## Please read the docs on how to use
    active: azure
  application:
    name: "wickedagile.reactiveOpenAPIMongo"
    processor:
      emitWaitNanos: 10
  data:
    mongodb:
      host: "localhost"
      port: 27017
      database: "quickstart"
logging:
  file:
    name: "application.log"
    path: "logs/"
  pattern:
    console: "%d %-5level %logger : %msg%n"
    file: "%d %-5level [%thread] %logger : %msg%n"
    level: INFO
  logback:
    rollingpolicy:
      file-name-pattern: "logs/application.%d{yyyy-MM-dd-HH-mm}.log"
      max-file-size: 1
      max-history: 2