server:
  port: 8080
management:
  security:
    enabled: false
  endpoints:
    web:
      exposure:
        include: "*"
springdoc:
  swagger-ui:
    path: /docs
spring:
  profiles:
    ## Potential options include kafka,
    active:
  application:
    name: "wickedagile.reactiveOpenAPIMongo"
    processor:
      emitWaitNanos: 10
  data:
    mongodb:
      host: "localhost"
      port: 27017
      database: "quickstart"
logging:
  file:
    name: "logs/application.log"
  pattern:
    console: "%d %-5level %logger : %msg%n"
    file: "%d %-5level [%thread] %logger : %msg%n"
  logback:
    rollingpolicy:
      file-name-pattern: "logs/application.%d{yyyy-MM-dd-HH-mm}.log"
#      max-file-size: 10M
      max-history: 2
  level:
    root: INFO
