spring:
  cloud:
    stream:
      bindings:
        auditor-in-0:
          group: ${spring.application.name}
        consumer-in-0:
          group: ${spring.application.name}
          destination: "vendorChange"
        producer-out-0:
          destination: "vendorChange"
      ## lots to configure to make production
      ## ready - https://github.com/spring-cloud/spring-cloud-stream-binder-kafka
      kafka:
        binder:
          brokers: localhost
          defaultBrokerPort: 9092
    function:
      definition: producer;consumer
